name: Release
on:
  push:
    tags:
    - '*'

  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build_artifacts.yml
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v3

      - name: Display structure of downloaded files
        run: ls -R

      - name: Create Release
        uses: ncipollo/release-action@v1.13.0
        with:
          allowUpdates: true
          removeArtifacts: true
          replacesArtifacts: true
          artifacts: '*-installer/VlcObsService.Installer.msi'
          


